"""Add programme_lead_feedback and ashwin_feedback columns

Revision ID: 1f1bc84dae50
Revises: 
Create Date: 2026-02-26 09:57:55.245899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f1bc84dae50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletter_editions', sa.Column('programme_lead_feedback', sa.Text(), nullable=True))
    op.add_column('newsletter_editions', sa.Column('ashwin_feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('newsletter_editions', 'ashwin_feedback')
    op.drop_column('newsletter_editions', 'programme_lead_feedback')
    # ### end Alembic commands ###
